services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
      - "9229:9229"  # Debug port
    volumes:
      - ./:/app
      - /app/node_modules
      - ./logs:/app/logs
    environment:
      - NODE_ENV=development
      - PORT=3001
    command: node --inspect=0.0.0.0:9229 server.js
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "7890:80"
    depends_on:
      - backend
    restart: unless-stopped
