services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
      - "9229:9229"  # Debug port
    volumes:
      - ./:/app
      - /app/node_modules
      - ./logs:/app/logs
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CERBO_API_BASE_URL=${CERBO_API_BASE_URL}
      - CERBO_API_AUTH_HEADER=${CERBO_API_AUTH_HEADER}
      - CORS_ORIGIN=http://localhost:7890  # Allow requests from frontend
    command: node --inspect=0.0.0.0:9229 server.js
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "7890:${FRONTEND_PORT:-3000}"
    environment:
      - PORT=${FRONTEND_PORT:-3000}
      - API_URL=${API_URL:-http://localhost:3001/api}
    volumes:
      - ./frontend:/app/src:ro  # Read-only mount for development
    depends_on:
      - backend
    restart: unless-stopped
